# Generated by Django 4.0.2 on 2022-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('walletAddress', models.CharField(max_length=200)),
                ('created', models.TimeField(auto_now_add=True)),
                ('last_updateed', models.TimeField(auto_now=True)),
                ('service_completed', models.IntegerField()),
                ('subscriber_count', models.IntegerField()),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
