# Generated by Django 4.0.2 on 2022-03-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='walletAddress',
            new_name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='service',
            name='image_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_path',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount_available',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
