# Generated by Django 4.0.2 on 2022-03-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('amount_available', models.IntegerField()),
                ('created', models.TimeField(auto_now_add=True)),
                ('last_updateed', models.TimeField(auto_now=True)),
                ('imagePath', models.CharField(max_length=200)),
                ('renewalRate', models.IntegerField()),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('startDate', models.TimeField()),
                ('fulfillmentDate', models.TimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
