# Generated by Django 4.0.2 on 2022-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essay',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
