# Generated by Django 4.0.2 on 2022-03-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_essay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(default='It is quite empty here', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
