# Generated by Django 4.0.2 on 2022-03-17 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_created_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='username',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.TimeField(default=datetime.datetime(2022, 3, 17, 16, 34, 18, 102137)),
        ),
    ]
