# Generated by Django 4.0.2 on 2022-03-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_services_rename_user_users_transactions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
