# Generated by Django 4.0.2 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=200),
        ),
    ]
