# Generated by Django 4.0.2 on 2022-03-17 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_service_username_service_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='activate',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='last_updateed',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='service',
            name='renewalRate',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.TimeField(default=datetime.datetime(2022, 3, 17, 16, 39, 21, 491830)),
        ),
    ]
