# Generated by Django 4.0.2 on 2022-03-15 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ratings_rating_rename_services_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.TimeField(default=datetime.datetime(2022, 3, 15, 15, 3, 39, 729698)),
        ),
    ]
