# Generated by Django 4.0.2 on 2022-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_fulfillmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fulfillmentDate',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
