# Generated by Django 4.0.2 on 2022-03-30 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_subscription_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
