# Generated by Django 4.0.2 on 2022-03-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_service_image_path_alter_user_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
