# Generated by Django 4.0.2 on 2022-04-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transaction_fulfillmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='essay',
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
