# Generated by Django 4.0.2 on 2022-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_service_image_path_alter_user_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
