# Generated by Django 4.0.2 on 2022-03-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_service_image_path_alter_user_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='biography',
        ),
    ]
