# Generated by Django 4.0.2 on 2022-03-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_bio_user_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='service_completed',
            new_name='services_completed',
        ),
    ]
