# Generated by Django 4.0.2 on 2022-03-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_service_completed_user_services_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pro_cost', models.IntegerField()),
                ('premium_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('free_amount', models.IntegerField(default=0)),
                ('pro_amount', models.IntegerField(default=0)),
                ('premium_amount', models.IntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscription')),
            ],
        ),
    ]
