# Generated by Django 4.0.2 on 2022-03-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscription_perk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='name',
        ),
        migrations.AddField(
            model_name='perk',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.service'),
            preserve_default=False,
        ),
    ]
