# Generated by Django 4.0.2 on 2022-03-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_perk_name_perk_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='premium_cost',
            new_name='premium_price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='pro_cost',
            new_name='pro_price',
        ),
    ]
