# Generated by Django 4.0.2 on 2022-03-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_premium_cost_subscription_premium_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='premium_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pro_price',
            field=models.IntegerField(null=True),
        ),
    ]
