# Generated by Django 4.0.2 on 2022-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_subscription_premium_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='premium_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pro_price',
            field=models.IntegerField(default=0),
        ),
    ]
