# Generated by Django 4.0.2 on 2022-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_subscription_premium_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
